"""
Test de cohérence de la numérotation Q1-Q20
"""
print("🧪 TEST DE COHÉRENCE Q1-Q20")
print("=" * 60)
print("")

print("📋 QUESTIONS DU FORMULAIRE:")
print("")
print("👤 Persona (Q1-Q4)")
print("  Q1: Nom")
print("  Q2: Prénom")
print("  Q3: Rôle/Fonction")
print("  Q4: Département")
print("")
print("💡 Contexte & Besoin (Q5-Q6)")
print("  Q5: Brief utilisateur")
print("  Q6: Exécution actuelle")
print("")
print("📊 Volumétrie (Q7-Q13)")
print("  Q7: Fréquence")
print("  Q8: Nb exécutions/occurrence")
print("  Q9: Temps unitaire")
print("  Q10: Nb personnes")
print("  Q11: Niveau irritant")
print("  Q12: Pourquoi irritant")
print("  Q13: Pourquoi urgent")
print("")
print("🔧 Nature (Q14-Q20)")
print("  Q14: Éléments sources")
print("  Q15: Action manuelle")
print("  Q16: Exemple action manuelle")
print("  Q17: Règles simples")
print("  Q18: Points complexes détaillés")
print("  Q19: Complexité orga")
print("  Q20: Outils")
print("")
print("=" * 60)
print("TOTAL: 20 questions (sans a/b)")
print("")

print("🎯 SCORING:")
print("  Impact Business (Q7+Q8+Q9+Q10) = /40")
print("  Faisabilité (Q17+count+Q19+Q15) = /30")
print("  Urgence (Q11×6) = /30")
print("  TOTAL = /100")
print("")
print("✅ Cohérence validée!")
